#!/bin/bash
echo updateing all 
sudo apt update -y 
sudo apt-get install gcc g++ -y 
echo checking installed versions: 
gcc --version 
g++ --version 
echo Installing... libjason-c-dev, sqlite3 and libcurl14-openssl-dev..
sudo apt-get install libjson-c-dev 
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install sqlite3
echo Done.. 
echo gcc makeing project now..
echo make al.c
gcc al.c  -o al -lcurl -lm 
echo make cl.c
gcc cl.c  -o cl
echo make de.c 
gcc de.c  -o de
echo make dl.c  
gcc dl.c -o dl
echo make fs.c
gcc fs.c -o fs
echo make me.c
gcc me.c -o me
echo make oz.c
gcc  oz.c -o oz -lm -lcurl -lsqlite3
echo make zs.c 
gcc zs.c -o zs -lm -lcurl -lsqlite3 
echo make dk.c  
gcc dk.c -o dk -lm -lcurl
echo make ix.c 
gcc ix.c -o ix -lm -lcurl -ljson-c
echo make tu.c 
gcc tu.c -o tu -lm -lcurl
echo make pc.c
gcc pc.c -o pc
echo make pl.c
gcc pl.c -o pl
echo make pt.c 
gcc pt.c -o pt -lm -lcurl
echo make up.c 
gcc up.c -o up
echo make zx.c 
gcc zx.c -o zx -lm -lcurl -lsqlite3
echo make ox.c 
gcc ox.c -o ox -lm -lcurl -lsqlite3
echo make zv.c 
gcc zv.c -o zv -lm -lcurl -lsqlite3
echo make zr.c 
gcc zr.c -o zr -lm -lcurl -lsqlite3 -std=c99
echo makeing randomx chat bot example / outline. 
gcc randomx.c -o randomx -lm -lsqlite3 
echo finished gcc build commands
